#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libmaxminddb
Version  : 1.3.2
Release  : 1
URL      : https://github.com/maxmind/libmaxminddb/releases/download/1.3.2/libmaxminddb-1.3.2.tar.gz
Source0  : https://github.com/maxmind/libmaxminddb/releases/download/1.3.2/libmaxminddb-1.3.2.tar.gz
Summary  : C library for the MaxMind DB file format
Group    : Development/Tools
License  : Apache-2.0 LGPL-3.0
Requires: libmaxminddb-bin = %{version}-%{release}
Requires: libmaxminddb-lib = %{version}-%{release}
Requires: libmaxminddb-license = %{version}-%{release}
Requires: libmaxminddb-man = %{version}-%{release}
BuildRequires : perl(IPC::Run3)

%description
All of these but the City and Enterprise files are JSON dumps of the databases
created by the GeoIP2 build integration tests
(TestFor::MM::Integration::GeoIP2::Build).

%package bin
Summary: bin components for the libmaxminddb package.
Group: Binaries
Requires: libmaxminddb-license = %{version}-%{release}
Requires: libmaxminddb-man = %{version}-%{release}

%description bin
bin components for the libmaxminddb package.


%package dev
Summary: dev components for the libmaxminddb package.
Group: Development
Requires: libmaxminddb-lib = %{version}-%{release}
Requires: libmaxminddb-bin = %{version}-%{release}
Provides: libmaxminddb-devel = %{version}-%{release}

%description dev
dev components for the libmaxminddb package.


%package lib
Summary: lib components for the libmaxminddb package.
Group: Libraries
Requires: libmaxminddb-license = %{version}-%{release}

%description lib
lib components for the libmaxminddb package.


%package license
Summary: license components for the libmaxminddb package.
Group: Default

%description license
license components for the libmaxminddb package.


%package man
Summary: man components for the libmaxminddb package.
Group: Default

%description man
man components for the libmaxminddb package.


%prep
%setup -q -n libmaxminddb-1.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550780814
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1550780814
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libmaxminddb
cp LICENSE %{buildroot}/usr/share/package-licenses/libmaxminddb/LICENSE
cp t/libtap/COPYING %{buildroot}/usr/share/package-licenses/libmaxminddb/t_libtap_COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mmdblookup

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libmaxminddb.so
/usr/lib64/pkgconfig/libmaxminddb.pc
/usr/share/man/man3/MMDB_aget_value.3
/usr/share/man/man3/MMDB_close.3
/usr/share/man/man3/MMDB_dump_entry_data_list.3
/usr/share/man/man3/MMDB_free_entry_data_list.3
/usr/share/man/man3/MMDB_get_entry_data_list.3
/usr/share/man/man3/MMDB_get_metadata_as_entry_data_list.3
/usr/share/man/man3/MMDB_get_value.3
/usr/share/man/man3/MMDB_lib_version.3
/usr/share/man/man3/MMDB_lookup_sockaddr.3
/usr/share/man/man3/MMDB_lookup_string.3
/usr/share/man/man3/MMDB_open.3
/usr/share/man/man3/MMDB_read_node.3
/usr/share/man/man3/MMDB_strerror.3
/usr/share/man/man3/MMDB_vget_value.3
/usr/share/man/man3/libmaxminddb.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmaxminddb.so.0
/usr/lib64/libmaxminddb.so.0.0.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libmaxminddb/LICENSE
/usr/share/package-licenses/libmaxminddb/t_libtap_COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mmdblookup.1
