#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: ab27b0e
#
Name     : libmaxminddb
Version  : 1.9.1
Release  : 12
URL      : https://github.com/maxmind/libmaxminddb/releases/download/1.9.1/libmaxminddb-1.9.1.tar.gz
Source0  : https://github.com/maxmind/libmaxminddb/releases/download/1.9.1/libmaxminddb-1.9.1.tar.gz
Summary  : C library for the MaxMind DB file format
Group    : Development/Tools
License  : Apache-2.0 CC-BY-SA-3.0 LGPL-3.0
Requires: libmaxminddb-bin = %{version}-%{release}
Requires: libmaxminddb-lib = %{version}-%{release}
Requires: libmaxminddb-license = %{version}-%{release}
Requires: libmaxminddb-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : perl(IPC::Run3)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
All of these but the City and Enterprise files are JSON dumps of the databases
created by the GeoIP2 build integration tests
(TestFor::MM::Integration::GeoIP2::Build).

%package bin
Summary: bin components for the libmaxminddb package.
Group: Binaries
Requires: libmaxminddb-license = %{version}-%{release}

%description bin
bin components for the libmaxminddb package.


%package dev
Summary: dev components for the libmaxminddb package.
Group: Development
Requires: libmaxminddb-lib = %{version}-%{release}
Requires: libmaxminddb-bin = %{version}-%{release}
Provides: libmaxminddb-devel = %{version}-%{release}
Requires: libmaxminddb = %{version}-%{release}

%description dev
dev components for the libmaxminddb package.


%package lib
Summary: lib components for the libmaxminddb package.
Group: Libraries
Requires: libmaxminddb-license = %{version}-%{release}

%description lib
lib components for the libmaxminddb package.


%package license
Summary: license components for the libmaxminddb package.
Group: Default

%description license
license components for the libmaxminddb package.


%package man
Summary: man components for the libmaxminddb package.
Group: Default

%description man
man components for the libmaxminddb package.


%prep
%setup -q -n libmaxminddb-1.9.1
cd %{_builddir}/libmaxminddb-1.9.1
pushd ..
cp -a libmaxminddb-1.9.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1704899379
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1704899379
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libmaxminddb
cp %{_builddir}/libmaxminddb-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libmaxminddb/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/libmaxminddb-%{version}/NOTICE %{buildroot}/usr/share/package-licenses/libmaxminddb/3c4407ddcf5d5e043ba639873d4dfacaf1af1c33 || :
cp %{_builddir}/libmaxminddb-%{version}/t/libtap/COPYING %{buildroot}/usr/share/package-licenses/libmaxminddb/f45ee1c765646813b442ca58de72e20a64a7ddba || :
cp %{_builddir}/libmaxminddb-%{version}/t/maxmind-db/LICENSE %{buildroot}/usr/share/package-licenses/libmaxminddb/cdf03962a1463e8d1a97ce306f8f267090298e9f || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/mmdblookup
/usr/bin/mmdblookup

%files dev
%defattr(-,root,root,-)
/usr/include/maxminddb.h
/usr/include/maxminddb_config.h
/usr/lib64/libmaxminddb.so
/usr/lib64/pkgconfig/libmaxminddb.pc
/usr/share/man/man3/MMDB_aget_value.3
/usr/share/man/man3/MMDB_close.3
/usr/share/man/man3/MMDB_dump_entry_data_list.3
/usr/share/man/man3/MMDB_free_entry_data_list.3
/usr/share/man/man3/MMDB_get_entry_data_list.3
/usr/share/man/man3/MMDB_get_metadata_as_entry_data_list.3
/usr/share/man/man3/MMDB_get_value.3
/usr/share/man/man3/MMDB_lib_version.3
/usr/share/man/man3/MMDB_lookup_sockaddr.3
/usr/share/man/man3/MMDB_lookup_string.3
/usr/share/man/man3/MMDB_open.3
/usr/share/man/man3/MMDB_read_node.3
/usr/share/man/man3/MMDB_strerror.3
/usr/share/man/man3/MMDB_vget_value.3
/usr/share/man/man3/libmaxminddb.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libmaxminddb.so.0.0.7
/usr/lib64/libmaxminddb.so.0
/usr/lib64/libmaxminddb.so.0.0.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libmaxminddb/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/libmaxminddb/3c4407ddcf5d5e043ba639873d4dfacaf1af1c33
/usr/share/package-licenses/libmaxminddb/cdf03962a1463e8d1a97ce306f8f267090298e9f
/usr/share/package-licenses/libmaxminddb/f45ee1c765646813b442ca58de72e20a64a7ddba

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mmdblookup.1
